name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false
      - run: ls -l
      - run: cat README.md