name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: dockerfileci:1.0.0
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t $IMAGE_NAME ./
      - run: docker container run $IMAGE_NAME npm run lint