name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - uses: mscoutermarsh/cowsays-action@master
        with:
          text: "Bonjour"
          color: "blue"
      - run: cat README.md | cowsays