name: Docker-CI
on:
  - push
jobs:
  container-test-job:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
